# Generated by Django 5.1.6 on 2025-03-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('engine_type', models.CharField(choices=[('benzyna', 'Benzynowy'), ('diesel', 'Diesel'), ('elektryk', 'Elektryczny'), ('hybryda', 'Hybrydowy')], max_length=50)),
                ('seats_count', models.PositiveSmallIntegerField()),
                ('gearbox_type', models.CharField(choices=[('manual', 'Manualna'), ('automat', 'Automatyczna')], max_length=50)),
                ('mileage_limit', models.PositiveIntegerField()),
                ('doors_count', models.PositiveIntegerField()),
                ('engine_power', models.PositiveSmallIntegerField()),
                ('engine_capacity', models.PositiveSmallIntegerField()),
                ('fuel_usage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=50)),
                ('body_type', models.CharField(choices=[('hatchbeck', 'hatchback'), ('sedan', 'kareta'), ('combi', 'combi'), ('suv', 'SUV')], max_length=50)),
                ('classification', models.CharField(choices=[('a', 'mini'), ('b', 'miejskie'), ('c', 'kompaktowe'), ('d', 'rodzinne'), ('e', 'wyższośrednie'), ('f', 'luksusowe'), ('s', 'sportowe'), ('h', 'kabriolety'), ('i', 'terenowe'), ('m', 'van')], max_length=50)),
                ('value', models.PositiveBigIntegerField()),
                ('availability', models.BooleanField()),
                ('trunk_capacity', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
